// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Device", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("advancedEnvironmentConditions")
                        .HasColumnType("bit");

                    b.Property<string>("deviceTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("failsafe")
                        .HasColumnType("bit");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("insertInto19InchCabinet")
                        .HasColumnType("bit");

                    b.Property<string>("installationPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("motionEnable")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("positionAxisNumber")
                        .HasColumnType("int");

                    b.Property<int>("rotationAxisNumber")
                        .HasColumnType("int");

                    b.Property<bool>("simaticCatalog")
                        .HasColumnType("bit");

                    b.Property<bool>("siplusCatalog")
                        .HasColumnType("bit");

                    b.Property<int>("tempMax")
                        .HasColumnType("int");

                    b.Property<int>("tempMin")
                        .HasColumnType("int");

                    b.Property<bool?>("terminalElement")
                        .HasColumnType("bit");

                    b.HasKey("_id");

                    b.ToTable("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
